# Generated by Django 2.2.19 on 2022-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20220308_1439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
